services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appointment_system

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080